apiVersion: solas.cluster.k8s.io/v1alpha1
kind: SolasMachineProviderSpec
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: solasmachineproviderspec-sample
spec:
  # Add fields here
  foo: bar
